# Generated by Django 5.1.5 on 2025-02-07 14:47

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=CKEditor5Field(config_name='default'),
        ),
    ]
