# Generated by Django 5.1.5 on 2025-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_quiz_created_at_quiz_created_by_quiz_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
