# Generated by Django 5.1.5 on 2025-02-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_lesson_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='uploaded_by',
            new_name='created_by',
        ),
    ]
