# Generated by Django 5.1.5 on 2025-02-19 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_lesson_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.TextField(default='This lesson preview needs to be updated. Please provide a short summary.', validators=[django.core.validators.MinLengthValidator(200), django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
