# Generated by Django 5.1.5 on 2025-02-19 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.TextField(help_text='A short preview of the lesson (200-300 characters)', validators=[django.core.validators.MinLengthValidator(200), django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
